export default {
  Explore: 'Explore',
  Bookmarks: 'Bookmarks',
  Post: 'Post',
  Messages: 'Messages',
  Profile: 'Profile',
  Login: 'Log In',
  LogInOrSignUp: 'Log In Or Sign Up',
  EnterPassword: 'Enter Password',
  FinishSigningUp: 'Finish Signing Up',
  EnterVerificationCode: 'Enter Verification Code',
  Tabs: 'Tabs',
  LogInOrSignUpScreens: 'LogInOrSignUpScreens',
  FilterResults: 'Filter Results',
  PostModal: 'PostModal',
  Prices: 'Prices',
  PostRentalScreens: 'PostRentalScreens',
  RentalDetails: 'Details',
};
